import{S as m,i as c}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&a(r)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();async function h(o){const s="https://pixabay.com",i="/api/",a="?key=43261756-f7e91f342fa994673ba6d269c",e=`&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`,t=s+i+a+e;try{const r=await fetch(t);if(!r.ok)throw new Error(r.statusText);return await r.json()}catch(r){throw console.error("Error fetching images:",r),r}}const n=document.querySelector(".gallery");function p(o){const s=o.map(({webformatURL:i,largeImageURL:a,tags:e,likes:t,views:r,comments:d,downloads:f})=>`<li class="gallery-item">
    <a class="gallery-link" href="${a}">
    <img class="gallery-img" src="${i}" alt="${e}">
    <div class="image-description">
    <p>likes: ${t}</p>
    <p>views: ${r}</p>    
    <p>comments: ${d}</p>
    <p>downloads: ${f}</p> 
    </div>
    </a>
    </li>`);n.insertAdjacentHTML("beforeend",s.join(""))}const u=new m(".gallery a");u.refresh();n.addEventListener("click",o=>{o.target.classList.contains("gallery-img")&&(o.preventDefault(),u.open())});const g=document.querySelector(".js-search"),l=document.querySelector(".loader");g.addEventListener("submit",y);async function y(o){o.preventDefault();const s=o.target.elementsr;n.innerHTML="",l.classList.remove("hidden");try{const i=await h(s);i.hits.length===0||s===""?c.show({title:"Error",message:'"Sorry, there are no images matching your search query. Please try again!"',position:"topRight",color:"#da1418",timeout:2e3}):p(i.hits)}catch{c.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"#da1418",timeout:2e3})}finally{l.classList.add("hidden")}}
//# sourceMappingURL=commonHelpers.js.map
